config/routes.rb
Rails.application.routes.draw do
  root "pages#landing"

  resources :users

  get "/reset" => "users#reset", as: "reset_password"

  post "/forgot_password" => "users#forgot_password"

  resources :sessions, :only => [:create]

  resources :buildings

  resources :posts

  get "/buildings/:id/admin" => "buildings#admin", as: "building_admin"

  get '/login' => "sessions#new"

  delete '/sessions' => 'sessions#destroy'
end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :users
  has_many :documents
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :building
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :building
  has_secure_password
  include BCrypt

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_digest = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    redirect_to root_path unless current_user
  end

  def check_admin
    if current_user
      redirect_to root_path unless current_user.building.id == 1
    else
      redirect_to root_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  def show
    @building = Building.find(params[:id])
    @posts = Post.where(building_id: params[:id]).order(created_at: :desc)
    @user = current_user
  end

  def admin
    @building = Building.find(params[:id])
    @post = Post.new
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def sign_in
    render :sign_in
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    if @post.save
      new_post(@post)
      return false
    else
      render :new
    end
  end

  def new_post(post)
    building = Building.where(id: post.building_id).first
    #UserMailer.new_memo(building).deliver
    redirect_to building_path(@post.building_id)
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :building_id, :created_at)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by({username: params[:user][:username]})
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to root_path
    end

  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #before_filter :authorize, except: [:new, :create]
  #before_filter :check_admin, only: [:new, :create]

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
    if @user.building_id == 1
      @buildings = Building.all
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    if params[:user]
      @user = User.create(user_params)
    else
      @user = User.create(username: params[:username], password: params[:password])
    end
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url  }
      format.json { head :no_content }
    end
  end

  def edit
  end

  def reset
  end

  def forgot_password
    @user = User.find_by_email(params[:email])
    random_password = Array.new(10).map { (65 + rand(58)).chr }.join
    @user.password = random_password
    @user.save!
    #UserMailer.password_reset(@user, random_password).deliver
    flash[:notice] = "Email with new password sent"
    redirect_to root_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render action: "edit"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :email, :building_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    session[:user_id]
  end

  def current_user?
    @user = User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/posts_controllers_helper.rb
module PostsControllersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/buildings/admin.html.erb
<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :placeholder => "Memo..." %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :placeholder => "Content...", :size => "70" %>
  </div>
  <div class="field">
    <%= f.hidden_field :building_id, :value => @building.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/show.html.erb
<h1> <%= @building.address %> </h1>

<div class="email_pm">
	<%= mail_to "propertymanager@tudorrealty.com", "Contact Property Manager" %>
</div>


<% if @user.building_id == 1 %>
	<div>
		<%= link_to "Admin", building_admin_path %>
	</div>
<% end %>

<% @posts.each do |post| %>
	<div class="post">
		<%= link_to(post.title + " - " + post.created_at.strftime("%B/%d/%Y"), controller: "posts", action: "show", id: post.id)%>
	</div>
<% end %>

app/views/layouts/_nav.html.erb
<div class="nav">
	<div class="left_nav">
		<h1> <%= link_to( "TRS", root_path, class: "logo" )%> </h1>
	</div>

	<div class="right_nav">
		<% if current_user? %>
			<div class="nav_link">
				<%= link_to("My Building", controller: "buildings", action: "show", id: @user.building_id)%>
			</div>
			<div class="nav_link">
				<%= link_to("My Profile", controller: "users", action: "show", id: @user.id)%>
			</div>
			<div class="nav_link">
				<%= link_to("Logout", sessions_path, :method => 'delete')%>
			</div>
		<% else %>
			<div class="nav_link">
				<%= link_to("Login", login_path) %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TudorConnect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "layouts/nav" unless current_page?("/") %>

<div class="content">
	<%= yield %>
</div>

</body>
</html>

app/views/pages/landing.html.erb
<div class="background_img">
	<%= image_tag "1.jpg"%>
</div>

<div class="welcome_text">

	<% if flash[:notice] %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>

	<h1> Welcome to Tudor Connect </h1>

	<% if current_user? %>
		<h1> <%= link_to("Enter", controller: "buildings", action: "show", id: @user.building_id)%> </h1>
	<% else %>
		<h1> <%= link_to("Enter", login_path) %> </h1>
	<% end %>

	<h4> <%= link_to("Forgot your password?", controller: "users", action: "reset") %> </h4>
</div>

<script>

	$(".content").css("background-color", "transparent")

</script>

app/views/posts/show.html.erb
<div class="post single_post">
	<h1> <%= @post.title %> </h1>

	<h1> <%= @post.created_at.strftime("Created on: %B/%d/%Y") %> </h1>

	<h1> <%= @post.body %> </h1>
</div>

<div class="back_button">
	<h1><%= link_to("Back", controller: "buildings", action: "show", id: @post.building_id)%></h1>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username, :placeholder => "username..." %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, :placeholder => "password..." %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :placeholder => "email..." %>
  </div>
  <div class="field">
    <%= f.label :building_id %><br>
    <%= f.text_field :building_id, :placeholder => "building id..." %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username, :placeholder => "username..." %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, :placeholder => "password..." %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :placeholder => "email..." %>
  </div>
  <div class="field">
    <%= f.label :building_id %><br>
    <%= f.text_field :building_id, :placeholder => "building id..." %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/reset.html.erb
<h1> Enter your email address: </h1>

<%= form_tag("forgot_password") do %>
	<div class="field">
		<%= label_tag :email %>
		<%= text_field_tag :email, params[:email]%>
	</div>
	<div class="actions"><%= submit_tag "Reset Password"%></div>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>

<h2> <%= @user.building.address %> </h2>

<h2> <%= link_to "Edit", edit_user_path %> </h2>

<div class="building_links">
	<% if @user.building_id == 1 %>
		<div class="new_user">
			<%= link_to "New User", new_user_path %>
		</div>
		<% @buildings.each do |building| %>
			<div class="building_link">
				<%= link_to("#{building.address}", building_path(building)) %><br>
			</div>
		<% end %>
	<% else %>
		<div class="building_link">
			<%= link_to("#{@user.building.address}", building_path(@user.building)) %>
		</div>
	<% end %>
</div>